version: "3.5"

services:
  media:
    container_name: shotit-media
    image: ghcr.io/shotit/shotit-media:v0.9.8
    restart: unless-stopped
    environment:
      - TRACE_MEDIA_SALT=${TRACE_MEDIA_SALT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    ports:
      - 3000:3000
    depends_on:
      - "minio"
    volumes:
      - type: bind
        source: ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/shotit-media
        target: /mnt/
    networks:
      shotit_net:

  minio:
    container_name: shotit-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    restart: unless-stopped
    environment:
      # - MINIO_ROOT_USER=${AWS_ACCESS_KEY}
      # - MINIO_ROOT_PASSWORD=${AWS_SECRET_KEY}
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_ETCD_ENDPOINTS=http://172.17.0.1:2379
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    entrypoint: sh
    # Local Minio Server, with initial bucket shotit-media
    command: -c 'mkdir -p /minio_data/shotit-media && minio server /minio_data --console-address ":9001"'
    # Remote Minio Gateway
    # command: -c 'minio gateway s3 ${AWS_ENDPOINT_URL} --console-address ":9001"'
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - "etcd"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      shotit_net:

  etcd:
    container_name: shotit-etcd
    image: quay.io/coreos/etcd:v3.5.0
    restart: unless-stopped
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    ports:
      - "2379:2379"
    networks:
      shotit_net:

networks:
  shotit_net:
    driver: bridge
